function startup()
    %{
    adds the necessary subdirectories of MSPM to MATLAB's PATH
    so that functions and code files can be called
    %}

    % Load in the paramaters file
if isfile('Config Files/parameters.mat')
    load('Config Files/parameters.mat', 'parameters')
    
    
    % Check if the save locations are valid and add location to path
    if isfolder(parameters.savelocation)
        addpath(genpath(parameters.savelocation));
    end
    
    if isfolder(parameters.runlocation)
        addpath(genpath(parameters.runlocation));
    end
    
end


addpath(...
    'Source Code',...
    'Source Code/enum',...
    'Source Code/Helper Function',...
    'Source Code/Saved Files',...
    'Source Code/Geometry',...
    'Source Code/MinorElements',...
    'Source Code/MajorElements',...
    'Source Code/Mechanical',...
    'Source Code/Function - Turb Nusselt',...
    'Source Code/Function - Turb Friction',...
    'Source Code/Function - Discretization',...
    'Source Code/GUI',...
    'Source Code/Simulation',...
    'Source Code/ListObjs',...
    'Source Code/Motion',...
    genpath('Test_Running'),...
    'Source Code/Relations',...
    'Source Code/Optimization',...
    'Source Code/Config Files'...
    );
%     'Function - Turb Cond Enhancement',...
%     'Function - Leakage',...
%     'Function - Laminar Nusselt',...
%     'Function - Laminar Friction',...
%     'Function - Laminar Cond Enhancement',...
%     'Function - Load Function',...

% mex anyEq.c -largeArrayDims;
end