function [runs] = Scaling_Test()
% title: String: Filename under which the test data will be saved
% simTime: double: Maximum simulation time over which the model will run
% SS: logical:  True/False on whether or not the model will stop on steady state
% movement_option: character: 'C' Continuous, 'V' Variable Speed
% rpm: Starting speed in RPMS
% max_dt = maximum timestep used by the model
% SourceTemp = Source Temperature assigned to model
% SinkTemp = Sink Temperature assigned to model
% EnginePressure = Pressure assigned to internal gas zones

%% Default parameters
runs(1) = struct(...
  'Model','EP_1 0,09 DP e0 PP e0',...
  'title','EP_1 0,09 DP e0 PP e0 - scale 0,5',...
  'simTime',4000,... [s]
  'SS',true,...
  'movement_option','C',...
  'rpm',60,... [rpm]
  'max_dt',0.1,... [s]
	'SourceTemp',90 + 273.15,... [K]
  'SinkTemp',5 + 273.15,... [K]
  'EnginePressure',101325,...
  'NodeFactor',1,...
  'Uniform_Scale',0.5);

runs(2) = struct(...
  'Model','EP_1 0,09 DP e0 PP e0',...
  'title','EP_1 0,09 DP e0 PP e0 - scale 1,0',...
  'simTime',4000,... [s]
  'SS',true,...
  'movement_option','C',...
  'rpm',60,... [rpm]
  'max_dt',0.1,... [s]
	'SourceTemp',90 + 273.15,... [K]
  'SinkTemp',5 + 273.15,... [K]
  'EnginePressure',101325,...
  'NodeFactor',1,...
  'Uniform_Scale',1.0);

runs(3) = struct(...
  'Model','EP_1 0,09 DP e0 PP e0',...
  'title','EP_1 0,09 DP e0 PP e0 - scale 1,5',...
  'simTime',4000,... [s]
  'SS',true,...
  'movement_option','C',...
  'rpm',60,... [rpm]
  'max_dt',0.1,... [s]
	'SourceTemp',90 + 273.15,... [K]
  'SinkTemp',5 + 273.15,... [K]
  'EnginePressure',101325,...
  'NodeFactor',1,...
  'Uniform_Scale',1.5);

runs(4) = struct(...
  'Model','EP_1 0,09 DP e0 PP e0',...
  'title','EP_1 0,09 DP e0 PP e0 - scale 2,0',...
  'simTime',4000,... [s]
  'SS',true,...
  'movement_option','C',...
  'rpm',60,... [rpm]
  'max_dt',0.1,... [s]
	'SourceTemp',90 + 273.15,... [K]
  'SinkTemp',5 + 273.15,... [K]
  'EnginePressure',101325,...
  'NodeFactor',1,...
  'Uniform_Scale',2);

runs(5) = struct(...
  'Model','EP_1 0,09 DP e0 PP e0',...
  'title','EP_1 0,09 DP e0 PP e0 - scale 3,0',...
  'simTime',4000,... [s]
  'SS',true,...
  'movement_option','C',...
  'rpm',60,... [rpm]
  'max_dt',0.1,... [s]
	'SourceTemp',90 + 273.15,... [K]
  'SinkTemp',5 + 273.15,... [K]
  'EnginePressure',101325,...
  'NodeFactor',1,...
  'Uniform_Scale',3);

runs(6) = struct(...
  'Model','EP_1 0,09 DP e0 PP e0',...
  'title','EP_1 0,09 DP e0 PP e0 - scale 4,0',...
  'simTime',4000,... [s]
  'SS',true,...
  'movement_option','C',...
  'rpm',60,... [rpm]
  'max_dt',0.1,... [s]
	'SourceTemp',90 + 273.15,... [K]
  'SinkTemp',5 + 273.15,... [K]
  'EnginePressure',101325,...
  'NodeFactor',1,...
  'Uniform_Scale',4);
end


