function [runs] = SensitivityTest2()
% title: String: Filename under which the test data will be saved
% simTime: double: Maximum simulation time over which the model will run
% SS: logical:  True/False on whether or not the model will stop on steady state
% movement_option: character: 'C' Continuous, 'V' Variable Speed
% rpm: Starting speed in RPMS
% max_dt = maximum timestep used by the model
% SourceTemp = Source Temperature assigned to model
% SinkTemp = Sink Temperature assigned to model
% EnginePressure = Pressure assigned to internal gas zones

%% Default parameters
runs(26) = struct(...
  'Model','EP_1 0,09 DP e0 PP e0 - DV',...
  'title','Sensitivity at 0 convection',...
  'simTime',1,... [s]
  'SS',true,...
  'movement_option','C',...
  'rpm',0.5,... [rpm]
  'max_dt',0.1,... [s]
	'SourceTemp',90 + 273.15,... [K]
  'SinkTemp',5 + 273.15,... [K]
  'EnginePressure',101325, ...
  'HX_Convection', 0.5, ...
  'Regen_Convection', 1, ...
  'Outside_Matrix_Convection', 1, ...
  'Friction', 0.5, ...
  'Solid_Conduction', 1, ...
  'Axial_Mixing_Coefficient', 1, ...
  'NodeFactor', double(1.0));

for i = 1:length(runs)
  runs(i) = runs(end);
end


