function startup()
    %{
    adds the necessary subdirectories of MSPM to MATLAB's PATH
    so that functions and code files can be called
    %}

    % Load in the paramaters file
if isfile('Config Files\parameters.mat')
    load('Config Files\parameters.mat', 'parameters')
    
    
    % Check if the save locations are valid and add location to path
    if isfolder(parameters.savelocation)
        addpath(genpath(parameters.savelocation));
    end
    
    if isfolder(parameters.runlocation)
        addpath(genpath(parameters.runlocation));
    end
    
end


addpath(...
    'enum',...
    'Helper Function',...
    'Saved Files',...
    'Geometry',...
    'MinorElements',...
    'MajorElements',...
    'Mechanical',...
    'Function - Turb Nusselt',...
    'Function - Turb Friction',...
    'Function - Discretization',...
    'GUI',...
    'Simulation',...
    'ListObjs',...
    'Motion',...
    genpath('Test_Running'),...
    'Relations',...
    'Optimization',...
    'Config Files'...
    );
%     'Function - Turb Cond Enhancement',...
%     'Function - Leakage',...
%     'Function - Laminar Nusselt',...
%     'Function - Laminar Friction',...
%     'Function - Laminar Cond Enhancement',...
%     'Function - Load Function',...

% mex anyEq.c -largeArrayDims;
end