classdef enumRelation
    enumeration
        Constant,...
            StackedShift,... % Unused
            Fixed,... % Unuseable
            AreaConstant,...
            Scaled,...
            LowestScaled,...
            Stroke,...
            Piston,...
            Width
    end
end

