function startup()
  addpath(...
    'enum',...
    'Helper Function',...
    'Saved Files',...
    'Geometry',...
    'MinorElements',...
    'MajorElements',...
    'Mechanical',...
    'Function - Turb Nusselt',...
    'Function - Turb Friction',...
    'Function - Discretization',...
    'GUI',...
    'Simulation',...
    'ListObjs',...
    'Motion',...
    'Test_Running',...
    'Relations',...
    'Optimization',...
    'Output Helpers'...
    );
  %     'Function - Turb Cond Enhancement',...
%     'Function - Leakage',...
%     'Function - Laminar Nusselt',...
%     'Function - Laminar Friction',...
%     'Function - Laminar Cond Enhancement',...
%     'Function - Load Function',...

  % mex anyEq.c -largeArrayDims;
end